name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit_test:
    name: NPM Unit Test
    uses: uc-cdis/.github/.github/workflows/npm_unit_test.yaml@master
    with:
      node-version: '14'
      npm-version: '8.5'
